name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 6 * * 1

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        framework: [ "net8.0-windows10.0.22621.0", "net9.0-windows10.0.22621.0" ]
      fail-fast: false
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: "9.x"
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -f ${{ matrix.framework }}
    - name: Test
      run: dotnet test --no-build --verbosity normal -f ${{ matrix.framework }}
    - name: Publish Windows (arm64/x64)
      run: |
        dotnet publish src/FacepunchCommitsMonitor.csproj -c Release -f ${{ matrix.framework }} -r win-x64 --nologo --self-contained
        dotnet publish src/FacepunchCommitsMonitor.csproj -c Release -f ${{ matrix.framework }} -r win-arm64 --nologo --self-contained
    - name: Upload Windows Builds
      uses: actions/upload-artifact@v4
      if: github.event_name == 'push'
      with:
        name: windows-builds-${{ matrix.framework }}
        path: |
          ${{ github.workspace }}/src/bin/Release/${{ matrix.framework }}/win-x64/publish/
          ${{ github.workspace }}/src/bin/Release/${{ matrix.framework }}/win-arm64/publish/
