name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 6 * * 1

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet: [ "6.x", "7.x", "8.x" ]
      fail-fast: false
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish Windows (arm64/x64)
      run: |
        dotnet publish src/FacepunchCommitsMonitor.csproj -c Release -r win-x64 --nologo --self-contained
        dotnet publish src/FacepunchCommitsMonitor.csproj -c Release -r win-arm64 --nologo --self-contained
    - name: Upload Windows Builds
      uses: actions/upload-artifact@v3
      if: github.event_name == 'push'
      with:
        name: windows-builds-dotnet-${{ matrix.dotnet }}
        path: |
          /home/runner/work/Facepunch-Commits-Monitor/Facepunch-Commits-Monitor/src/bin/Release/net8.0/win-x64/publish/
          /home/runner/work/Facepunch-Commits-Monitor/Facepunch-Commits-Monitor/src/bin/Release/net8.0/win-arm64/publish/
